### ISSUE TITLE
File too short to be a zip file: 0

### ISSUE THREAD

**Issue by vaziliybober** [mertakdut/EpubParser#31]
reader.setFullContent("android.resource://" + getPackageName() + "/" + "harry.epub");

at the above line i get this exception. There is an absolute absence of information about it in Google. I need your help badly:

04-25 12:10:20.139 13561-13561/com.example.vazil.learnersreader W/System.err: com.github.mertakdut.exception.ReadingException: Error initializing ZipFile: File too short to be a zip file: 0
        at com.github.mertakdut.Reader.fillContent(Reader.java:296)
        at com.github.mertakdut.Reader.setFullContent(Reader.java:54)
        at com.example.vazil.learnersreader.MainActivity.onCreate(MainActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:6915)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by vaziliybober** [comment]
Sorry for being an idiot. The path just doesn't exist. With a correct path everything works just fine. Thanks for an amazing library!
